### ISSUE TITLE
采集到不存在的页面时报错

### ISSUE THREAD

**Issue by coder-liyang** [jae-jae/QueryList#33]
我们程序中的链接有些是从页面中抓取的,这样就无法保证每个链接/每个域名都真实有效,这时候应该给出一个错误提示,而不应该直接报错,终止程序.
```
in /html/vendor/jaeger/querylist/QueryList.php:193

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(1024, 'The received co...', '/html...', 193, Array)
#1 /html/vendor/jaeger/querylist/QueryList.php(193): trigger_error('The received co...', 1024)
#2 /html/vendor/jaeger/querylist/QueryList.php(87): QL\QueryList->_query('http://www.haha...', Array, '', 'UTF-8', NULL, false)
#3 /html/commands/HahaController.php(54): QL\QueryList::Query('http://www.haha...', Array, '', 'UTF-8')
#4 [internal function]: app\commands\HahaController->actionTest()
#5 /html/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 /html/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#7 /html/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('test', Array)
#8 /html/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('test', Array)
#9 /html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('haha/test', Array)
#10 /html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('haha/test', Array)
#11 /html/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /html/yii(19): yii\base\Application->run()
#13 {main}

```

**Comment by jae-jae** [comment]
QueryLIst只是抛出了一个`Notice `并没有终止程序，终止程序的是你用的框架。

**Comment by coder-liyang** [comment]
我觉得报notice也不应该,毕竟这会影响外层程序的正常执行.更好的做法应该是返回false,同时将错误赋值给一个专门的属性.

**Comment by jae-jae** [comment]
V4版本已改成抛出HTTP异常，可以自己捕获异常进行处理
